config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'main#index'
  resources :tpl, :only => [:index]

  get 'san-pham/:id' => 'main#product', as: :product
  get 'tat-ca-san-pham' => 'main#all', as: :all_products
  get 'tat-ca-san-pham/:page' => 'main#all', as: :all_products_page
  get 'loai-san-pham/:id' => 'main#all', as: :type
  get 'loai-san-pham/:id/:page' => 'main#all', as: :type_page
  get 'ket-qua-tim-kiem' => 'main#all', as: :search
  match '/lien-he', to: 'contacts#index', via: 'get', as: :contacts
  match '/lien-he', to: 'contacts#create', via: 'post', as: :contacts_post
  get 'dich-vu', to: 'main#service', as: :service
  get 'bai-viet/:id', to: 'main#blog', as: :blog
  get 'bai-viet/:id/:page', to: 'main#blog', as: :blog_page
  get 'noi-dung-bai-viet/:id', to: 'main#blog_detail', as: :blog_detail
  namespace :admin do
    root to: 'page#index', via: :get
    resources :services
    resources :blogs
    
    resources :users, :only => [:index] do
      post :login, to: "users#login_success", on: :collection
      get :logout, to: "users#logout", on: :collection
    end
  end

  namespace :api do
    scope :v1, module: 'v1', as: 'v1' do
      get 'api1'
      get 'api2'
      post 'api3'
      post 'api4'
      post 'api5'
      get 'api6'
      post 'api7'
      post 'api8'
    end
  end

end

app/views/part/_breadcrumbs.html.slim
ul.breadcrumbs
  li
    = link_to 'Trang chủ', root_path
  li
    = link_to 'Tất cả sản phẩm', all_products_path
  - if @keyword.present?
    li
      = link_to 'Kết quả tìm kiếm của ' + @keyword, root_path
  - unless type.nil?
    li
      = link_to type.name, type_path(type.id)
  - unless product.nil?
    li
      = link_to product.name , product_path(product.id)

app/views/part/_pagination.html.slim
ul.c-pagination
  - class_prev = @page == 1 ? 'hide' : ''
  li.prev class="#{class_prev}"
    - if @type.present?
      = link_to '<' , type_page_path(id: @id, page: @page-1)
    - elsif @blog_type.present?
      = link_to '<' , blog_page_path(id: @id, page: @page-1)
    - else
      = link_to '<' , all_products_page_path(@page-1)
  - (1..@total).each do |num|
    - class_pagi = @page == num ? 'm-active' : ''
    li class="#{class_pagi}"
      - if @type.present?
        = link_to num , type_page_path(id: @id, page:num)
      - elsif @blog_type.present?
        = link_to num , blog_page_path(id: @id, page:num)
      - else
        = link_to num , all_products_page_path(num)
  - class_next = @page == @total ? 'hide' : ''
  li.next class="#{class_next}"
    - if @type.present?
      = link_to '>' , type_page_path(id: @id, page:@page+1)
    - elsif @blog_type.present?
      = link_to '>' , blog_page_path(id: @id, page:@page+1)
    - else
      = link_to '>' , all_products_page_path(@page+1)

app/views/part/_side_bar.html.slim
aside#sidebar
  .sidebar-widget.sidebar-cart
    h3.widget-title Bán chạy nhất
    .widget-content
      ul.cart-product-list
        - @best_products.each do |product|
          li
            .cart-product
              p.product-image
                = link_to product_path(product.id)
                  = image_tag product.image_url, alt: product.name
              h4.product-title
                = link_to product.name , product_path(product.id)
              / p.product-price
              /   | #{product.price}.000VND
  .sidebar-widget.sidebar-search
    h3.widget-title Tìm kiếm
    .widget-content
      = form_tag(search_path, :method => "get", class: "c-search-form") do
        .form-fields
          = text_field_tag :keyword, params[:keyword], class: "keyword", placeholder: "Tên sản phẩm..."
          button.c-button type="submit" 
            i.fa.fa-search
  .sidebar-widget.sidebar-links
    h3.widget-title Theo loại
    .widget-content
      ul
        - @types = Type.all
        - @types.each do |type|
          li class="type-product#{type.id}"
            = link_to type.name, type_path(type.id)

app/views/part/_side_bar_blog.html.slim
aside#sidebar
  .sidebar-widget.sidebar-cart
    h3.widget-title Bài viết được xem nhiều
    .widget-content
      ul.cart-product-list
        - best_view = Blog.order(views: :desc).limit(4)
        - best_view.each do |best|
          li
            .cart-product
              p.product-image
                = link_to blog_detail_path(best.id)
                  = image_tag best.image_title(:small), alt: best.title
              h4.product-title
                = link_to best.title, blog_detail_path(best.id)
              p.product-price
                = best.created_at.strftime('%Y-%m-%d %H:%M')
  .sidebar-widget.sidebar-links
    h3.widget-title Categories
    .widget-content
      ul
      - categories = Type.kind('blog').displayed
      - categories.each do |cg|
        li class="type-blog#{cg.id}"
          = link_to cg.name, blog_path(id: cg.id)
  .sidebar-widget.sidebar-cart
    h3.widget-title Bài viết mới
    .widget-content
      ul.cart-product-list
        - news = Blog.order(created_at: :desc).limit(4)
        - news.each do |new|
          li
            .cart-product
              p.product-image
                = link_to blog_detail_path(new.id)
                  = image_tag new.image_title(:small), alt: new.title
              h4.product-title
                = link_to new.title, blog_detail_path(new.id)
              p.product-price
                = new.created_at.strftime('%Y-%m-%d %H:%M')
  