config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'main#index'
  resources :tpl, :only => [:index]

  get 'san-pham/:id' => 'main#product', as: :product
  get 'tat-ca-san-pham' => 'main#all', as: :all_products
  get 'tat-ca-san-pham/:page' => 'main#all', as: :all_products_page
  get 'loai-san-pham/:id' => 'main#all', as: :type
  get 'loai-san-pham/:id/:page' => 'main#all', as: :type_page
  get 'ket-qua-tim-kiem' => 'main#all', as: :search
  match '/lien-he', to: 'contacts#index', via: 'get', as: :contacts
  match '/lien-he', to: 'contacts#create', via: 'post', as: :contacts_post
  get 'dich-vu', to: 'main#service', as: :service
  get 'bai-viet/:id', to: 'main#blog', as: :blog
  get 'bai-viet/:id/:page', to: 'main#blog', as: :blog_page
  get 'noi-dung-bai-viet/:id', to: 'main#blog_detail', as: :blog_detail
  namespace :admin do
    root to: 'page#index', via: :get
    resources :services
    resources :blogs
    
    resources :users, :only => [:index] do
      post :login, to: "users#login_success", on: :collection
      get :logout, to: "users#logout", on: :collection
    end
  end

  namespace :api do
    scope :v1, module: 'v1', as: 'v1' do
      get 'api1'
      get 'api2'
      post 'api3'
      post 'api4'
      post 'api5'
      get 'api6'
      post 'api7'
      post 'api8'
    end
  end

end

app/views/admin/part/_menu.html.slim
= stylesheet_link_tag 'admin/application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'angular_js', 'data-turbolinks-track' => true
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation" 
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target="#sidebar-collapse" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#" 
        span> Lipans
        | Admin
      ul.user-menu
        li.dropdown.pull-right
          a.dropdown-toggle data-toggle="dropdown" href="#" 
            svg.glyph.stroked.male-user
              use xlink:href="#stroked-male-user" 
            = @user.email
            span.caret
          ul.dropdown-menu role="menu"
            li
              = link_to logout_admin_users_path
                svg.glyph.stroked.cancel
                  use xlink:href="#stroked-cancel" 
                | Logout
#sidebar-collapse.col-sm-3.col-lg-2.sidebar
  ul.nav.menu
    li#home
      = link_to admin_root_path
        svg.glyph.stroked.dashboard-dial
          use xlink:href="#stroked-dashboard-dial" 
        | Trang chủ
    li#services
      = link_to admin_services_path
        svg.glyph.stroked.calendar
          use xlink:href="#stroked-calendar" 
        | Dịch vụ
    li#blogs
      = link_to admin_blogs_path
        svg.glyph.stroked.pencil
          use xlink:href="#stroked-pencil" 
        | Blog

javascript:
  $('.user-menu .dropdown-toggle').mouseenter(function(){
      $('.user-menu .dropdown-menu').show();
  });
  $('.user-menu .dropdown-menu').mouseleave(function(){
    $(this).hide();
  });
  