config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'main#index'
  resources :tpl, :only => [:index]

  get 'san-pham/:id' => 'main#product', as: :product
  get 'tat-ca-san-pham' => 'main#all', as: :all_products
  get 'tat-ca-san-pham/:page' => 'main#all', as: :all_products_page
  get 'loai-san-pham/:id' => 'main#all', as: :type
  get 'loai-san-pham/:id/:page' => 'main#all', as: :type_page
  get 'ket-qua-tim-kiem' => 'main#all', as: :search
  match '/lien-he', to: 'contacts#index', via: 'get', as: :contacts
  match '/lien-he', to: 'contacts#create', via: 'post', as: :contacts_post
  get 'dich-vu', to: 'main#service', as: :service
  get 'bai-viet/:id', to: 'main#blog', as: :blog
  get 'bai-viet/:id/:page', to: 'main#blog', as: :blog_page
  get 'noi-dung-bai-viet/:id', to: 'main#blog_detail', as: :blog_detail
  namespace :admin do
    root to: 'page#index', via: :get
    resources :services
    resources :blogs
    
    resources :users, :only => [:index] do
      post :login, to: "users#login_success", on: :collection
      get :logout, to: "users#logout", on: :collection
    end
  end

  namespace :api do
    scope :v1, module: 'v1', as: 'v1' do
      get 'api1'
      get 'api2'
      post 'api3'
      post 'api4'
      post 'api5'
      get 'api6'
      post 'api7'
      post 'api8'
    end
  end

end

app/views/layouts/_footer.html.slim
#bottom-panel
  .bottom-panel-inner
    .container
      .row
        .col-md-6
          .bottom-text.various-content
            h3 Liên hệ
            p
              | Địa chỉ: 13/13B Nguyễn Thị Thập F.6 Tp. Mỹ Tho, Tiền Giang
              br
              | DĐ: 098 7225 372
              br
              | Số tài khoản: 067 100 0423 806 - Đinh Thị Kim Phượng - Vietcombank Tiền Giang
        .col-md-6
          .bottom-subscribe.various-content
            h3 Mỹ phẩm Li-pans
            | Hãy gửi email hoặc gọi điện thoại trực tiếp cho Li-pans để được tư vấn miễn phí và liên hệ đặt hàng
            br
            | E-mail: kimphuong43@gmail.com
            br
              | Hotline:(073) 3876 237
footer#footer
  .container
    .footer-bottom
      .row
        .col-md-6.col-md-push-6
          nav.footer-menu
            ul
              li
                = link_to 'Trang chủ', root_path
              li
                = link_to 'Tất cả sản phẩm', all_products_path
              li
                = link_to 'Spa', service_path
              li
                = link_to 'Bài viết chia sẻ', blog_path('tat-ca')
              li
                = link_to 'Liên hệ', contacts_path
        .col-md-6.col-md-pull-6
          .footer-text
            p
              | DNTN.
              = link_to 'Đinh Thị Kim Phượng', root_path

app/views/layouts/_header.html.slim
header#header.m-animated
  .header-bg
    .header-inner
      .header-branding
        = link_to root_path
          = image_tag 'logo_header.png', width: 291
      .header-navigation
        nav.header-menu
          button.header-menu-toggle type="button" 
            i.fa.fa-bars
            | MENU
          ul
            li#home
              span
                = link_to 'Trang chủ', root_path
            li#all-products
              span
                = link_to 'Tất cả sản phẩm', all_products_path
            li#type.m-has-submenu
              span
                = link_to 'Theo loại', all_products_path
              ul.sub-menu
                - types = Type.kind('product').displayed
                - types.each do |type|
                  li class="type-product#{type.id}"
                    = link_to type.name, type_path(type.id)
            li#service
              span
                = link_to 'Spa', service_path
            li#blog.m-has-submenu
              span
                = link_to 'Bài viết chia sẻ', blog_path('tat-ca')
              ul.sub-menu
                - blogs = Type.kind('blog').displayed
                - blogs.each do |blog|
                  li class="type-blog#{blog.id}"
                    = link_to blog.name, blog_path(blog.id)
            li#contacts
              span 
                = link_to 'Liên hệ', contacts_path
        .header-search.sidebar-search
          .header-search-inner
            = form_tag(search_path, :method => "get", class: "search-form") do
              i.search-ico.fa.fa-search
              = text_field_tag :keyword, params[:keyword], class: "search-input", placeholder: "Tên sản phẩm..."
              button.search-submit type="submit" 
                i.fa.fa-angle-right
              button.search-toggle type="button"  Tìm kiếm
          button.search-toggle-mobile type="button" 
            i.fa
      .header-panel
        button.header-panel-toggle type="button" 
          i.fa
        .header-reservation          
          = link_to 'Mỹ phẩm Li-pans', root_path, class: 'c-button'
        .header-contact
          ul
            li
              .item-inner
                i.ico.fa.fa-phone
                strong (073) 3876 237
            li
              .item-inner
                i.ico.fa.fa-envelope-o
                a href="#"  kimphuong43@gmail.com
            li
              .item-inner
                i.ico.fa.fa-map-marker
                strong DNTN. ĐINH THỊ KIM PHƯỢNG
                br
                | 13/13B Nguyễn Thị Thập, F.6
                br
                | Tp. Mỹ Tho, T. Tiền Giang
            li
              .item-inner
                i.ico.fa.fa-clock-o
                dl
                  dt Hotline:
                  dd 098 7225 372
        .header-social
          ul
            li
              a href="#" title="Twitter" 
                i.fa.fa-twitter
            li
              a href="#" title="Facebook" 
                i.fa.fa-facebook
            li
              a href="#" title="Pinterest" 
                i.fa.fa-pinterest

app/views/layouts/application.html.slim
doctype html
html
  head
    title Lipans
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body ng-app="Lipans"
    = yield